(ns offcourse.fake-data.buzzwords)

(def buzzwords ["4G"
               "Aggregator"
               "Agile"
               "Ajax"
               "Algorithm"
               "Benchmarking"
               "Back-end"
               "Beta"
               "Big Data"
               "Bleeding edge"
               "Clickthrough"
               "Cloud"
               "Collaboration"
               "Content Management System"
               "Convergence"
               "Cross-platform"
               "Datafication"
               "Data science"
               "Deep dive"
               "Deep web"
               "Design pattern"
               "Dev Ops"
               "Digital divide"
               "Disruptive Technologies"
               "Dot-bomb"
               "E-learning"
               "Engine"
               "Framework"
               "Folksonomy"
               "Fuzzy logic"
               "Immersion"
               "Internet of Things"
               "Innovation"
               "Mashup"
               "Mobile"
               "Modularity"
               "Nanotechnology"
               "Netiquette"
               "Next Generation"
               "Pandering"
               "Parsing"
               "PaaS"
               "Podcasting"
               "Portal"
               "Real-time"
               "Responsive"
               "Sensorization"
               "SaaS"
               "Scalability"
               "Skeuomorphic"
               "Social bookmarking"
               "Social software"
               "Spam"
               "Struts"
               "Sync-up"
               "Tagging"
               "Transmedia"
               "User generated content"
               "Viral"
               "Virtualization"
               "Vlogging"
               "Vortal"
               "Webinar"
               "Web services"
               "Wikiality"
               "Workflow"])
